### ISSUE TITLE
IFC/ifcXML Validation for Brick PDT Sample file

### ISSUE THREAD

**Issue by UPiccinno** [buildingSMART/ProductData#29] opened 2018-10-10 10:45 UTC
1.	We tried to validate our sample brick PDT file (“IFCXML4_TEMPLATE-brick.ifcXML” https://github.com/buildingSMART/ProductData/tree/master/SampleFiles/HC%20(Italy)/Sample%20PDT%20ifcXML) getting this opening error:
“2018-10-08 10:45:59,433 ERROR - Parser failure: Unexpected type Elements.”
2.	We tried to validate your ifcXML sample on Github (https://github.com/buildingSMART/ProductData/tree/master/SampleFiles/CernySamples/Example7) getting a positive result (no error) with the SchemaValidator Tool
3.	We edited our brick’s sample ifcXML (“IFCXML4_TEMPLATE-brick - Validator.ifcXML”, starting from the same of point 1) following the same Prolog of your example (point 2)
4.	We tried to validate this edited ifcXML but we got the same error message.
                                                             
                                                             .......

what I’m obtaining now is:

“2018-10-09 16:25:20,610 INFO  - Validating file: C:\Users\piccinno\Desktop\TC442_WG2_IFCXML\00-IFCXML\08-IFCXML_def\IFCXML4_TEMPLATE-brick.ifcXML
2018-10-09 16:25:20,625 INFO  - File format: XML (*.ifcXML)
2018-10-09 16:25:21,547 ERROR - Parser failure: Unexpected type Elements.
Check finished. There are 1 errors.”

Just to check, I’m using the SchemaValidator tool released October 7th, are we working with the same release?

About the error that you get, I agree about the presence of only “IfcDerivedUnitElement” into “IfcDerivedUnit”(highlighted entities). Creating a derived unit as a combination of unit whose type is an “IfcSIUnit” according to xsi namespace, I’ve obtained the following structure:

 ![imm1](https://user-images.githubusercontent.com/38915287/46731070-079bbc00-cc8a-11e8-8231-772dd93e9cab.png)

Could this structure respect both schemas?

                                                         .........

Your data snippet is invalid compared to both XSD and EXPRESS:

 <xs:element name="IfcDerivedUnit" type="ifc:IfcDerivedUnit" substitutionGroup="ifc:Entity" nillable="true"/>
 <xs:complexType name="IfcDerivedUnit">
  <xs:complexContent>
   <xs:extension base="ifc:Entity">
    <xs:sequence>
     <xs:element name="Elements">
      <xs:complexType>
       <xs:sequence>
        <xs:element ref="ifc:IfcDerivedUnitElement" maxOccurs="unbounded"/>    IfcDerivedUnitElement
       </xs:sequence>
       <xs:attribute ref="ifc:itemType" fixed="ifc:IfcDerivedUnitElement"/>    IfcDerivedUnitElement
       <xs:attribute ref="ifc:cType" fixed="set"/>
       <xs:attribute ref="ifc:arraySize" use="optional"/>
      </xs:complexType>
     </xs:element>
    </xs:sequence>
    <xs:attribute name="UnitType" type="ifc:IfcDerivedUnitEnum" use="optional"/>
    <xs:attribute name="UserDefinedType" type="ifc:IfcLabel" use="optional"/>
   </xs:extension>
  </xs:complexContent>
 </xs:complexType>

ENTITY IfcDerivedUnit;
  Elements : SET [1:?] OF IfcDerivedUnitElement;                  IfcDerivedUnitElement
  UnitType : IfcDerivedUnitEnum;
  UserDefinedType : OPTIONAL IfcLabel;
 DERIVE
  Dimensions : IfcDimensionalExponents := IfcDeriveDimensionalExponents(Elements);
 WHERE
  WR1 : (SIZEOF (Elements) > 1) OR ((SIZEOF (Elements) = 1) AND (Elements[1].Exponent <> 1 ));
  WR2 : (UnitType <> IfcDerivedUnitEnum.USERDEFINED) OR
((UnitType = IfcDerivedUnitEnum.USERDEFINED) AND 
(EXISTS(SELF.UserDefinedType)));
END_ENTITY;

I would have thought that your data wouldn’t pass through XSD schema check either. If it did I would question its abilities.

                                                                .............

**Comment by UPiccinno** [comment] 2018-10-10 10:58
@martin1cerny good morning,
We're trying to validate each snippet of *.ifcXML (indicated at point 1 in the starting text of the issue) with your SchemaValidator.
Actually our XML editor is validating the same file according to "IFC4_ADD2-schema.xsd".
Could you please describe how you tool works? (format conversions, validating input schemas/files)
Could you kindly explain us which is the official EXPRESS Specification your tool is referring to?

Thank you very much

**Comment by martin1cerny** [comment] 2018-10-10 11:40
My tool is using the official version of [EXPRESS schema for IFC4 Add2](http://www.buildingsmart-tech.org/ifc/IFC4/Add2/IFC4_ADD2.exp). XSD schema is inferred from EXPRESS schema and contains only very small subset of schema constraints compared to the main EXPRESS definitions.

My validation tool uses [xBIM Toolkit](https://github.com/xBimTeam/XbimEssentials) to read the file and to run all validation checks. xBIM this uses early binding where the model schema is represented as C# classes, structures and interfaces. Because your XML is not valid it fails to load the data at first place.

The tool runs several levels of checking:
 1) Syntax checking (is the file well structured - only for STEP21 files)
 2) Are object type assignments valid (When attribute is of certain type, is the object you are trying to assign of the required type)
 3) Mandatory attributes (are mandatory attributes non-empty)
 4) Cardinality checking (are cardinality constrains fulfilled)
 5) Schema 'WHERE' rules checking (additional functional constrains defined in the documentation and EXPRESS schema like: `UniquePropertySetNames : (NOT(EXISTS(HasPropertySets))) OR IfcUniquePropertySetNames(HasPropertySets);` for [IfcTypeObject](http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/link/ifctypeobject.htm))
 6) Additional checks (valid unit types used for specific value types and property template specifications for example. Those are not defined in the schema but probably should be)

I'm surprised your tool didn't find a problem in the data because as you can see in the documentation of [IfcDeriverUnit](http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/link/ifcderivedunit.htm) Elements should only be of type `IfcDerivedUnitElement`. The same can be found in the complete [XSD schema for IFC4 Add2](http://www.buildingsmart-tech.org/ifc/IFC4/Add2/IFC4_ADD2.xsd).

```xml
<xs:element name="IfcDerivedUnit" type="ifc:IfcDerivedUnit" substitutionGroup="ifc:Entity"
 nillable="true"/>
 <xs:complexType name="IfcDerivedUnit">
  <xs:complexContent>
   <xs:extension base="ifc:Entity">
    <xs:sequence>
     <xs:element name="Elements">
      <xs:complexType>
       <xs:sequence>
        <xs:element ref="ifc:IfcDerivedUnitElement" maxOccurs="unbounded"/>
       </xs:sequence>
       <xs:attribute ref="ifc:itemType" fixed="ifc:IfcDerivedUnitElement"/>
       <xs:attribute ref="ifc:cType" fixed="set"/>
       <xs:attribute ref="ifc:arraySize" use="optional"/>
      </xs:complexType>
     </xs:element>
    </xs:sequence>
    <xs:attribute name="UnitType" type="ifc:IfcDerivedUnitEnum" use="optional"/>
    <xs:attribute name="UserDefinedType" type="ifc:IfcLabel" use="optional"/>
   </xs:extension>
  </xs:complexContent>
 </xs:complexType>
```

**Comment by klacol** [comment] 2018-10-10 18:57
Thanks for the contribution.

The main error was, that the ref attribute in the IfcDerivedUnitElement must be set within the element at the SiUnit. And the attribute ```UnitType="userdefined"``` was missing.

```XML
 <IfcDerivedUnit id="idCM0" UnitType="userdefined" UserDefinedType="Thermal conductivity">
  <Elements>
   <IfcDerivedUnitElement Exponent="1">
    <Unit xsi:type="IfcSIUnit" ref="id06"/>
   </IfcDerivedUnitElement>
   <IfcDerivedUnitElement Exponent="-1">
    <Unit xsi:type="IfcSIUnit" ref="id07" />
   </IfcDerivedUnitElement>
   <IfcDerivedUnitElement Exponent="-1">
    <Unit xsi:type="IfcSIUnit" ref="id01"/>
   </IfcDerivedUnitElement>
  </Elements>
 </IfcDerivedUnit>
```
I have changed the sample file, so that it can be parsed now. There many more errors remaining and can be solved now.

**Comment by klacol** [comment] 2018-10-10 18:59
I have commented the ```<IfcUnitAssignment>``` out, since it is not clear for me, if and how ```IfcDerivedUnit``` should be set there.

**Comment by klacol** [comment] 2018-10-10 19:02
The remaining validation errors can be seen [here](https://ci.appveyor.com/project/klacol/productdata/branch/master#L905).

**Comment by martin1cerny** [comment] 2018-10-11 05:13
Just a note: If the XML element represents reference to an instance of the entity defined elsewhere it should also have an attribute `xsi:nil="true"`.

```xml
<Unit xsi:type="IfcSIUnit" ref="id01" xsi:nil="true"/>
```

**Comment by UPiccinno** [comment] 2018-10-29 09:52
Good morning @martin1cerny,

I'm quite finishing my ifcXML validation with xBIM tool.
One common error still unsolved is referred to structures like this:

![immagine](https://user-images.githubusercontent.com/38915287/47642045-e979fb00-db67-11e8-98b7-9570fa8bd3ac.png)

and the error is:

![immagine](https://user-images.githubusercontent.com/38915287/47642158-365dd180-db68-11e8-977e-d7f2ae89c944.png)

The IfcSimplePropertyTemplate is structured into an IfcComplexPropertyTemplate that is in a IfcPropertySettemplate.

Do you have suggestions to avoid the error?
Thans in advance,

Ugo

**Comment by martin1cerny** [comment] 2018-10-29 10:06
Can you share a wider context of your snippet? This error refers to assignment of this `IfcSimplePropertyTemplate` in its outer scope, not the internal structure.

**Comment by UPiccinno** [comment] 2018-10-29 10:10
yes of course:

 <IfcPropertySetTemplate Name="Dichiarazione di prestazione" GlobalId="xxxxxxxxxxxxxxxxxxxx13">
         <HasPropertyTemplates>
          <IfcComplexPropertyTemplate GlobalId="xxxxxxxxxxxxxxxxxxxx46">
           <HasPropertyTemplates>
            <IfcComplexPropertyTemplate Name="Stabilità dimensionale" Description="Spostamento dovuto all'umidità" id="idTP9" GlobalId="0ME3R5NET1rwM2mEToEDc2">
             <HasPropertyTemplates>
              <IfcSimplePropertyTemplate Name="Stabilità dimensionale_function" GlobalId="xxxxxxxxxxxxxxxxxxxx53"> 
               <Enumerators Name="Function">
                <EnumerationValues>
                 <IfcLabel-wrapper> &lt;= </IfcLabel-wrapper>
                </EnumerationValues>
               </Enumerators>
              </IfcSimplePropertyTemplate>
              <IfcSimplePropertyTemplate Name="Stabilità dimensionale_value" GlobalId="xxxxxxxxxxxxxxxxxxxx54"> 
               <Enumerators Name="Value">
                <EnumerationValues>
                 <IfcLengthMeasure-wrapper>0.500</IfcLengthMeasure-wrapper>
                </EnumerationValues>
                <Unit>
                 <IfcDerivedUnit ref="idCM2">
                  <Elements>
                   <IfcDerivedUnitElement>
                    <Unit xsi:type="IfcSIUnit"/>
                   </IfcDerivedUnitElement>
                  </Elements>
                 </IfcDerivedUnit>
                </Unit>
               </Enumerators>
              </IfcSimplePropertyTemplate>
             </HasPropertyTemplates>
            </IfcComplexPropertyTemplate>
               
            <IfcSimplePropertyTemplate Name="Forza di adesione" Description="per utilizzo in componenti soggetti a requisiti strutturali" id="idTP10" GlobalId="3vHjuooT0Hsm00051Mm008"> 
             <Enumerators Name="Value">
              <EnumerationValues>
               <IfcPressureMeasure-wrapper>0.15</IfcPressureMeasure-wrapper>
              </EnumerationValues>
              <Unit>
               <IfcSIUnit ref="id02"/>
              </Unit>
             </Enumerators>
            </IfcSimplePropertyTemplate>  
           </HasPropertyTemplates>
          </IfcComplexPropertyTemplate>
         </HasPropertyTemplates>
        </IfcPropertySetTemplate> 

I have used the same structure also before, obtaining no errors with the validator tool.

thank you

ugo

**Comment by UPiccinno** [comment] 2018-10-29 10:13
![immagine](https://user-images.githubusercontent.com/38915287/47643388-a3bf3180-db6b-11e8-8996-694a28f68b52.png)
![immagine](https://user-images.githubusercontent.com/38915287/47643410-b8032e80-db6b-11e8-9102-ec839e3eaaa3.png)

**Comment by UPiccinno** [comment] 2018-10-29 15:56
Sorry for the delay: attached the zip file of my ifcXML. "Comments" are parts that still need to be validated.
Excluding the last IfcSimplePropertyTemplate all previous entities are validated.

[Brick_Sample_SchemaValidator.zip](https://github.com/buildingSMART/ProductData/files/2525989/Brick_Sample_SchemaValidator.zip)

thank you

Ugo

**Comment by martin1cerny** [comment] 2018-10-29 17:03
xBIM might be confused by the fact you put data in elements which are actually only references. As far as I know expected way it to set these to be xs:nil and leave them as empty elements. I'll investigate in the core tomorrow and will make xBIM to ignore any content in `ref` elements. This way the xBIM XML reader might just go out of sync.

**Comment by martin1cerny** [comment] 2018-10-31 14:31
I have implemented a change in xBIM ifcXML reader so that it consumes the content of reference elements if there is any. Once my latest PR #32 is merged your file should pass with no errors.

**Comment by klacol** [comment] 2018-11-01 07:08
I have merged the PR #32. It [looks better now](https://ci.appveyor.com/project/klacol/productdata/branch/master#L898).

The errors with the units are not shown aymore.

The file [IFCXML4_TEMPLATE-brick.ifcXML](https://github.com/buildingSMART/ProductData/blob/master/SampleFiles/HC%20(Italy)/Sample%20PDT%20ifcXML/IFCXML4_TEMPLATE-brick.ifcXML) has still many other errors, mostly related to missing Guids ore Enum names.

IMHO the following expression could lead to missunderstandings. The reader of the unit has always to follow the ref and should ignore the definition that is included directly in the IfcDerivedUnit 

```xml
<IfcDerivedUnit ref="idCM2">
 <Elements>
  <IfcDerivedUnitElement>
   <Unit xsi:type="IfcSIUnit"/>
  </IfcDerivedUnitElement>
 </Elements>
</IfcDerivedUnit>
```

Even if the Validator ignores now the expression within the IfcDerivedUnit, this expression is not needed. Therefore the above expression should be changed to this according to the remark by @martin1cerny:

```xml
<IfcDerivedUnit ref="idCM2" xsi:nil="true"/>
```

**Comment by martin1cerny** [comment] 2018-11-01 08:03
Putting any data in the `ref` element is misleading because anything in there should be ignored. So, if anybody tries to modify the content it will lead to unexpected behaviour as only the main definition will be used and the rest would be ignored.

**Comment by martin1cerny** [comment] 2018-11-01 09:28
I think this issue can be closed now.

**Comment by TLiebich** [comment] 2018-11-01 13:45
in my view, this is an error (as already indicated):
`<IfcDerivedUnit ref="idCM2">
 <Elements>
`
either it refers to another definition, but then it has to be nil=true, or it shall not have a ref attribute. A validator should show an error here.

correct would be
```
<IfcDerivedUnit ref="idCM2" xsi:nil="true" />
```
or
```
<IfcDerivedUnit id="idCM3">
 <Elements>
```

**Comment by martin1cerny** [comment] 2018-11-02 07:42
Thanks @TLiebich . I'll have a look if I could easily report it just as a warning. I think it should not be a fatal error in the parser. But I agree that if we want to use these files as informative examples it should not show a bad practise which other people might follow.

**Comment by klacol** [comment] 2018-11-02 09:29
Thank you @martin1cerny 
https://ci.appveyor.com/project/klacol/productdata/builds/19997452#L1008

> WARN  - Reference to element IfcDerivedUnit, ref='20' is not empty. This is a wrong practise.

**Comment by martin1cerny** [comment] 2018-11-02 09:42
You are very fast with PR merges @klacol :-)

**Comment by klacol** [comment] 2018-11-02 10:15
> You are very fast with PR merges @klacol :-)

@martin1cerny you are fast with your conbributions. I can see then in Appveyor immideately the result of the PR before the merge and can then merge the PR without risk.

**Comment by UPiccinno** [comment] 2018-11-05 08:35
thanks everyone for help and contribution. @klacol I'm updating my ifcXML, due to submit the validate file as soon as possible.

**Comment by klacol** [comment] 2018-11-23 22:31
Ok, the file is valid now:
https://ci.appveyor.com/project/klacol/productdata/branch/master#L1038

Thanks

**Closed by klacol** 2018-11-23 22:31 UTC
